-- Flyway V1 — Application schema only (no flyway_schema_history here)

-- ===== Tables =====

CREATE TABLE IF NOT EXISTS match_format (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    advantage BOOLEAN NOT NULL,
    number_of_sets_to_win INTEGER NOT NULL CHECK (number_of_sets_to_win >= 1),
    games_per_set INTEGER NOT NULL CHECK (games_per_set >= 1), -- Changed from points_per_set to match MatchFormat.java
    super_tie_break_in_final_set BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS player (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    birth_year INTEGER,
    points INTEGER,
    ranking INTEGER
);

CREATE TABLE IF NOT EXISTS score (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE IF NOT EXISTS set_score (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_index INTEGER,
    team_a_score INTEGER NOT NULL,
    team_b_score INTEGER NOT NULL,
    tie_break_team_a INTEGER,
    tie_break_team_b INTEGER,
    score_id BIGINT REFERENCES score(id)
);

-- Helpful index for set_score lookups
CREATE INDEX IF NOT EXISTS idx_set_score_score_id ON set_score(score_id);

CREATE TABLE IF NOT EXISTS tournament (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    owner_id VARCHAR(191) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    city VARCHAR(50),
    club VARCHAR(50),

    -- enums stored as strings to match @Enumerated(EnumType.STRING)
    gender VARCHAR(16),
    level VARCHAR(32),

    start_date DATE,
    end_date DATE,

    -- JSON configuration (validated as an object)
    config JSONB,
    CONSTRAINT tournament_config_is_object CHECK (config IS NULL OR jsonb_typeof(config) = 'object')
);

CREATE INDEX IF NOT EXISTS idx_tournament_owner ON tournament(owner_id);
CREATE INDEX IF NOT EXISTS idx_tournament_config_gin ON tournament USING GIN (config);

CREATE TABLE IF NOT EXISTS round (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_index INTEGER,
    match_format_id BIGINT UNIQUE REFERENCES match_format(id),
    tournament_id BIGINT REFERENCES tournament(id),
    stage VARCHAR(255) CHECK (
      (stage)::text = ANY ((ARRAY['GROUPS'::varchar, 'Q1'::varchar, 'Q2'::varchar, 'Q3'::varchar, 'R64'::varchar, 'R32'::varchar, 'R16'::varchar, 'QUARTERS'::varchar, 'SEMIS'::varchar, 'FINAL'::varchar, 'WINNER'::varchar])::text[])
    )
);

-- helpful index for round lookups by tournament
CREATE INDEX IF NOT EXISTS idx_round_tournament_id ON round(tournament_id);

CREATE TABLE IF NOT EXISTS pool_ranking (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
);


CREATE TABLE IF NOT EXISTS pool (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    pool_ranking_id BIGINT UNIQUE REFERENCES pool_ranking(id),
    round_id BIGINT REFERENCES round(id),
    name VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_pool_round_id ON pool(round_id);


CREATE TABLE IF NOT EXISTS player_pair (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_index INTEGER,
    seed INTEGER,
    type VARCHAR(16) DEFAULT 'NORMAL', -- Added for PairType enum
    player1_id BIGINT REFERENCES player(id),
    player2_id BIGINT REFERENCES player(id),
    pool_id BIGINT REFERENCES pool(id) ON DELETE SET NULL,
    tournament_id BIGINT REFERENCES tournament(id)
);

CREATE INDEX IF NOT EXISTS idx_player_pair_tournament_id ON player_pair(tournament_id);
CREATE INDEX IF NOT EXISTS idx_player_pair_pool_id ON player_pair(pool_id);

CREATE TABLE IF NOT EXISTS pool_ranking_details (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_index INTEGER,
    points INTEGER NOT NULL,
    set_average INTEGER NOT NULL,
    player_pair_id BIGINT REFERENCES player_pair(id),
    pool_ranking_id BIGINT REFERENCES pool_ranking(id)
);

CREATE INDEX IF NOT EXISTS idx_pool_ranking_details_pair_id ON pool_ranking_details(player_pair_id);
CREATE INDEX IF NOT EXISTS idx_pool_ranking_details_ranking_id ON pool_ranking_details(pool_ranking_id);


CREATE TABLE IF NOT EXISTS game (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_index INTEGER,
    scheduled_time TIME(6) WITHOUT TIME ZONE,
    -- stored as string to match @Enumerated(EnumType.STRING)
    winner_side VARCHAR(16),
    format_id BIGINT REFERENCES match_format(id),
    pool_id BIGINT REFERENCES pool(id) ON DELETE SET NULL,
    round_id BIGINT REFERENCES round(id) ON DELETE CASCADE,
    score_id BIGINT UNIQUE REFERENCES score(id),
    teama_id BIGINT REFERENCES player_pair(id) ON DELETE SET NULL,
    teamb_id BIGINT REFERENCES player_pair(id) ON DELETE SET NULL,
    court VARCHAR(255)
);

-- helpful indexes for common joins/lookups
CREATE INDEX IF NOT EXISTS idx_game_round_id ON game(round_id);
CREATE INDEX IF NOT EXISTS idx_game_pool_id ON game(pool_id);
CREATE INDEX IF NOT EXISTS idx_game_teama_id ON game(teama_id);
CREATE INDEX IF NOT EXISTS idx_game_teamb_id ON game(teamb_id);

-- End V1