-- Create user_favorite_tournament table
CREATE TABLE user_favorite_tournament (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    tournament_id BIGINT NOT NULL,
    added_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (tournament_id) REFERENCES tournament(id) ON DELETE CASCADE,
    UNIQUE (user_id, tournament_id)
);

CREATE INDEX idx_user_favorite_tournament_user ON user_favorite_tournament(user_id);
CREATE INDEX idx_user_favorite_tournament_tournament ON user_favorite_tournament(tournament_id);

-- Create user_favorite_game table
CREATE TABLE user_favorite_game (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    game_id BIGINT NOT NULL,
    added_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (game_id) REFERENCES game(id) ON DELETE CASCADE,
    UNIQUE (user_id, game_id)
);

CREATE INDEX idx_user_favorite_game_user ON user_favorite_game(user_id);
CREATE INDEX idx_user_favorite_game_game ON user_favorite_game(game_id);

